#!/bin/bash

PROJECT_NAME=$1
TEMPLATE_PROJECT_NAME=TemplateProject
CMAKE_FILE=CMakeLists.txt
GOOGLETEST_PATH=/d/workspace/googletest

cp -R ${TEMPLATE_PROJECT_NAME} ${PROJECT_NAME}
cp -R ${GOOGLETEST_PATH} ${PROJECT_NAME}/unit_tests/lib/

pushd ${PROJECT_NAME}
sed 's/'$TEMPLATE_PROJECT_NAME'/'$PROJECT_NAME'/g' ${CMAKE_FILE} > ${CMAKE_FILE}_
mv ${CMAKE_FILE}_ ${CMAKE_FILE}
popd

pushd ${PROJECT_NAME}/src
mv ${TEMPLATE_PROJECT_NAME}.h ${PROJECT_NAME}.h
mv ${TEMPLATE_PROJECT_NAME}.cpp ${PROJECT_NAME}.cpp
sed 's/'$TEMPLATE_PROJECT_NAME'/'$PROJECT_NAME'/g' ${PROJECT_NAME}.cpp > ${PROJECT_NAME}.cpp_
mv ${PROJECT_NAME}.cpp_ ${PROJECT_NAME}.cpp
sed 's/'$TEMPLATE_PROJECT_NAME'/'$PROJECT_NAME'/g' ${PROJECT_NAME}.h > ${PROJECT_NAME}.h_
mv ${PROJECT_NAME}.h_ ${PROJECT_NAME}.h
sed 's/TEMPLATEPROJECT/'${PROJECT_NAME^^}'/g' ${PROJECT_NAME}.h > ${PROJECT_NAME}.h_
mv ${PROJECT_NAME}.h_ ${PROJECT_NAME}.h
sed 's/'$TEMPLATE_PROJECT_NAME'/'$PROJECT_NAME'/g' ${CMAKE_FILE} > ${CMAKE_FILE}_
mv ${CMAKE_FILE}_ ${CMAKE_FILE}
popd

pushd ${PROJECT_NAME}/unit_tests
sed 's/'$TEMPLATE_PROJECT_NAME'/'$PROJECT_NAME'/g' ${CMAKE_FILE} > ${CMAKE_FILE}_
mv ${CMAKE_FILE}_ ${CMAKE_FILE}
popd

pushd ${PROJECT_NAME}/unit_tests/tests
mv ${TEMPLATE_PROJECT_NAME}_test.cpp ${PROJECT_NAME}_test.cpp
sed 's/'$TEMPLATE_PROJECT_NAME'/'$PROJECT_NAME'/g' ${CMAKE_FILE} > ${CMAKE_FILE}_
mv ${CMAKE_FILE}_ ${CMAKE_FILE}
popd

